spring:
  application:
    name: my-spring-ai
  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY:YOUR_VALID_KEY}
        chat:
          options:
            #model: gemini-2.5-flash-lite
            model: gemini-2.5-flash
            max-tokens: 5000
            max-output-tokens: 10000
        embedding:
          project-id: gen-lang-client-0474182412
#          project-id: gen-lang-client-0293244803
          location: us-central1
          text:
            options:
              model: text-embedding-004

    vectorstore:
      in-memory:
        enabled: true

  servlet:
    multipart:
      max-file-size: 3MB

server:
  port: 8080

# Trace the cache hit and miss.
logging:
  level:
    org:
      springframework:
        cache: trace